---
title: "Total Energy"
author: "John Grando"
date: "October 19, 2020"
output: 
  html_document:
    keep_md: true
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RColorBrewer)
library(kableExtra)
library(gridExtra)
library(forecast)
library(ggplot2)
library(sparklyr)
library(dplyr)
library(tidyr)
```

```{r}
sc <- sparklyr::spark_connect(
  master = 'local[2]', 
  spark_home = Sys.getenv("SPARK_HOME"))
total_energy_df <- sparklyr::spark_read_parquet(
  sc = sc, 
  name = 'total_energy_df', 
  path = "hdfs://localhost:9000/Processed/TotalEnergyDF")
total_energy_df <- select(
    total_energy_df, 
    "date", 
    "name", 
    "value", 
    "units") %>% 
  mutate(
    date = as.date(date),
    value = as.numeric(value)) %>% 
  arrange(date)
```

```{r}
electricity_net_generation_df <- total_energy_df %>% 
  dplyr::filter(date > as.Date("1990-01-01")) %>% 
  dplyr::filter(name %rlike% "(Electricity Net Generation From.*All Sectors$)")
```

```{r eval=FALSE}
electricity_net_generation_df %>% 
  dplyr::filter(is.na(value) | value == '') %>% 
  dplyr::count(name = "null fields") %>% 
  kable('html') %>% 
  kable_styling(
    bootstrap_options = 'striped',
    full_width = FALSE,
    position = "center",
    font_size = 20)
```


```{r}
date_limit_df <- electricity_net_generation_df %>% 
  group_by() %>% 
  dplyr::summarize(
    min_date = min(date), 
    max_date = max(date)) %>% 
  sparklyr::collect()
```


```{r}
electricity_net_generation_pivot_df <- electricity_net_generation_df %>% 
  dplyr::mutate(
    name = regexp_replace(name, '^Electricity Net Generation From (.*), All Sectors$', 'eng_$1'),
    name = tolower(name)
  ) %>% 
  mutate(
    name = regexp_replace(name, ' ', '_')
  ) %>% 
  sdf_pivot(
    formula = date ~ name, 
    fun.aggregate = list(value = "mean"))

```

```{r fig.width=12}
color_values <- colorspace::diverge_hcl(n = 12, c = 100, l = c(20,90), power = 1)

electricity_net_generation_pivot_melted_df <- electricity_net_generation_pivot_df %>% 
    collect() %>% 
    gather(key = "id", value = 'val', -c(date))

plot_theme <- theme(plot.title = element_text(hjust = 0.5, size = 25),
        plot.subtitle = element_text(hjust = 0.5, size = 14),
        strip.text = element_text(size = 20),
        plot.background = element_rect(fill = "lightgrey"), 
        panel.background = element_rect(fill = "white"), 
        panel.grid.major.x = element_line(color = "lightgrey"), 
        panel.grid.major.y = element_line(color = "lightgrey"), 
        axis.text = element_text(size=14, color = "grey1"), 
        axis.title = element_text(size=16, color = "grey1"))

ggplot(
  data = electricity_net_generation_pivot_melted_df, 
  mapping = aes(x = date, y = val, color = id)) +
  geom_line() +
  scale_color_manual(values = color_values) +
  labs(x = "Date", y = "Million kWh") +
  ggtitle("Electricity Net Generation") +
  plot_theme
```

```{r}
electricity_net_generation_pivot_reduced_df <- electricity_net_generation_df %>% 
  filter(date > as.Date('2010-01-01')) %>% 
  dplyr::mutate(
    name = regexp_replace(name, '^Electricity Net Generation From (.*), All Sectors$', 'eng_$1'),
    name = tolower(name)) %>% 
  mutate(
    name = regexp_replace(name, ' ', '_')
  ) %>% 
  mutate(
    name = ifelse(
      name %in% c(
        "eng_coal", 
        "eng_natural_gas", 
        "eng_nuclear_electric_power"), 
      name, 
      "eng_other")
  ) %>% 
  sdf_pivot(
    formula = date ~ name, 
    fun.aggregate = list(value = "mean"))

date_limit_reduced_df <- electricity_net_generation_pivot_reduced_df %>% 
  group_by() %>% 
  dplyr::summarize(
    min_date = min(date), 
    max_date = max(date)) %>% 
  sparklyr::collect()
```

```{r fig.width=12}
electricity_net_generation_pivot_melted_df <- electricity_net_generation_pivot_reduced_df %>% 
    collect() %>% 
    gather(key = "id", value = 'val', -c(date))
ggplot(
  data = electricity_net_generation_pivot_melted_df, 
  mapping = aes(x = date, y = val, color = id)) +
  geom_line() +
  scale_color_manual(values = color_values) +
  labs(x = "Date", y = "Million kWh") +
  ggtitle("Electricity Net Generation - Reduced Categories") +
  plot_theme
```


```{r}
eng_coal_ts <- ts(
  data = electricity_net_generation_pivot_reduced_df %>%  
    arrange(date) %>% 
    select("eng_coal") %>% 
    collect() %>% 
    pull("eng_coal"), 
  start = c(
    as.numeric(format(date_limit_reduced_df["min_date"][[1]], "%Y")), 
    as.numeric(format(date_limit_reduced_df["min_date"][[1]], "%m"))),
  end = c(
    as.numeric(format(date_limit_reduced_df["max_date"][[1]], "%Y")), 
    as.numeric(format(date_limit_reduced_df["max_date"][[1]], "%m"))),
  frequency = 12)
```

```{r fig.width=12}
ggseasonplot(eng_coal_ts, polar=TRUE) +
  scale_color_manual(values=color_values) +
  ggtitle("Seasonal Coal Generation") +
  plot_theme
```

```{r fig.width=12}
autoplot(eng_coal_ts, series='original') + 
  labs(x = "Year", y = "Million kWh") +
  ggtitle("Electricity Net Generation From Coal") +
  scale_color_manual(values=color_values) +
  plot_theme
```

```{r fig.width=12}
acf_plot <- ggAcf(eng_coal_ts) + 
  plot_theme +
  ggtitle("ACF")
pacf_plot <- ggPacf(eng_coal_ts) +
  plot_theme +
  ggtitle("PACF")
grid.arrange(acf_plot, pacf_plot, ncol=2)
```


```{r}
#f_xreg <- fourier(eng_coal_ts,K = 5)
p_xreg <- matrix(
  c(
    electricity_net_generation_pivot_reduced_df %>% select('eng_natural_gas') %>% pull(),
    electricity_net_generation_pivot_reduced_df %>% select('eng_nuclear_electric_power') %>% pull()),
  ncol=2, 
  byrow = FALSE
)

#export for hyperparameters
save(eng_coal_ts, p_xreg, file = paste("../RFiles/Data/total_energy_coal_data.RData", sep="/"))

#try out differencing?  it is definitely not stationary
fit <- auto.arima(eng_coal_ts, xreg = p_xreg)

checkresiduals(fit)
summary(fit)
```

```{r fig.width=12}
#Adjust future predictors
predict_l <- 24
amplifier <- 1.5
n_amplifier <- 1.5

tst <- tail(
  electricity_net_generation_pivot_reduced_df %>% select('eng_natural_gas') %>% pull(), predict_l)
new_tst <- tst * tst[1] / tail(tst,1) * seq(from = 1, to = amplifier, length.out = predict_l)
new_n_tst <- tail(electricity_net_generation_pivot_reduced_df %>% select('eng_nuclear_electric_power') %>% pull(), predict_l) * seq(from = 1, to = n_amplifier, length.out = predict_l)
new_p_xreg <- matrix(
  c(
    new_tst,
    new_n_tst),
  ncol=2, 
  byrow = FALSE
)

train_fit <- forecast(
    fit,
    h = predict_l, 
    xreg=new_p_xreg)

autoplot(train_fit) +
  autolayer(
    ts(
      c(electricity_net_generation_pivot_reduced_df %>% select('eng_natural_gas') %>% pull()),
      start = c(
    as.numeric(format(date_limit_reduced_df["min_date"][[1]], "%Y")), 
    as.numeric(format(date_limit_reduced_df["min_date"][[1]], "%m"))),
      frequency = 12),
    series = 'natural gas') +
  autolayer(
    ts(
      new_tst,
      start = c(
    as.numeric(format(date_limit_reduced_df["max_date"][[1]], "%Y")), 
    as.numeric(format(date_limit_reduced_df["max_date"][[1]], "%m"))),
      frequency = 12),
    series = 'natural gas prediction'
  ) +
  autolayer(
    ts(
      c(electricity_net_generation_pivot_reduced_df %>% select('eng_nuclear_electric_power') %>% pull()),
      start = c(
    as.numeric(format(date_limit_reduced_df["min_date"][[1]], "%Y")), 
    as.numeric(format(date_limit_reduced_df["min_date"][[1]], "%m"))),
      frequency = 12),
    series = 'nuclear') +
  autolayer(
    ts(
      new_n_tst,
      start = c(
    as.numeric(format(date_limit_reduced_df["max_date"][[1]], "%Y")), 
    as.numeric(format(date_limit_reduced_df["max_date"][[1]], "%m"))),
      frequency = 12),
    series = 'nuclear prediction'
  ) +
  coord_cartesian(xlim=c(2010,2025), ylim = c(0,2.5e+05)) +
  scale_color_manual(values=color_values) +
  labs(x = "Date", y = "Million kWh") +
  ggtitle(
    as.character(train_fit), 
    subtitle = paste("\nAmplification (NG): ", amplifier, ", Amplification (Nuclear): ", n_amplifier)) +
  plot_theme
```

